#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
BUTTON_NAMES = {
    0: "a",
    1: "b",
    10: "l2",
    13: "pad_down",
    14: "pad_left",
    15: "pad_right",
    12: "pad_up",
    11: "r2",
    4: "select",
    5: "start",
    6: "thumbl",
    7: "thumbr",
    8: "tl",
    9: "tr",
    2: "x",
    3: "y",
}
